<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Attribute_Set_Main $this */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3><?= $this->escapeHtml($this->_getHeader()) ?></h3></td>
            <td class="form-buttons">
                <?= $this->getBackButtonHtml() ?>
                <?= $this->getResetButtonHtml() ?>
                <?= $this->getDeleteButtonHtml() ?>
                <?= $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<table cellspacing="0" width="100%">
    <tr>
        <td width="360" style="border-right:1px solid #ddd; padding:0 23px 23px 0;" class="edit-attribute-set">
            <?= $this->getSetFormHtml() ?>
        </td>
        <td width="320" style="border-right:1px solid #ddd; padding:0 23px 23px 23px;">
            <div class="content-header skip-header">
            <table cellspacing="0">
                    <tbody>
                        <tr>
                            <td><h3><?= Mage::helper('catalog')->__('Groups') ?></h3></td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <?php if (!$this->getIsReadOnly()): ?>
                <p><?= $this->getAddGroupButton() ?>&nbsp;<?= $this->getDeleteGroupButton() ?></p>
                <p class="note-block"><?= Mage::helper('catalog')->__('Double click on a group to rename it') ?></p>
            <?php endif ?>

            <div id="tree-div1" style="width:320px;height:500px;margin-top:5px;overflow:auto"></div>
        </td>
        <td style="padding:0 0 23px 23px;">
            <div class="content-header skip-header">
                <table cellspacing="0">
                    <tbody>
                        <tr>
                            <td><h3><?= Mage::helper('catalog')->__('Unassigned Attributes') ?></h3></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div id="tree-div2" style="height:550px;margin-top:5px;overflow:auto"></div>
        </td>
    </tr>
</table>

<script type="text/javascript">
document.addEventListener('DOMContentLoaded', () => {
    const setForm = new EavAttributeSetForm('tree-div1', 'tree-div2');

    setForm.buildGroupTree(<?= $this->getGroupTreeJson() ?>);
    setForm.buildAttributeTree(<?= $this->getAttributeTreeJson() ?>);


    window.editSet = {

    }

});
</script>
