<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Create_Data $this */
?>
<div class="order-grid">
    <div class="switcher">
        <label for="currency_switcher"><?= Mage::helper('sales')->__('Order Currency:') ?></label>
        <select id="currency_switcher" name="order[currency]" onchange="order.setCurrencyId(this.value); order.setCurrencySymbol(this.options[this.selectedIndex].getAttribute('symbol'));">
        <?php foreach ($this->getAvailableCurrencies() as $_code): ?>
            <option value="<?= $_code ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif ?> symbol="<?= $this->getCurrencySymbol($_code) ?>"><?= $this->getCurrencyName($_code) ?></option>
        <?php endforeach ?>
        </select>
        <script type="text/javascript">
            order.setCurrencySymbol('<?= Mage::helper('core')->jsQuoteEscape($this->getCurrencySymbol($this->getCurrentCurrencyCode())) ?>');
        </script>
    </div>

    <div id="order-additional_area" style="display:none" class="order-additional-area">
        <?= $this->getChildHtml('additional_area') ?>
    </div>

    <div id="order-search" style="display:none" class="order-search-items">
        <?= $this->getChildHtml('search') ?>
    </div>

    <div id="order-items"><?= $this->getChildHtml('items') ?></div>

    <div id="order-errors"><?= $this->getChildHtml('errors') ?></div>

    <div id="order-form_account">
        <?= $this->getChildHtml('form_account') ?>
    </div>

    <div id="order-billing_address"><?= $this->getChildHtml('billing_address') ?></div>
    <div id="order-shipping_address"><?= $this->getChildHtml('shipping_address') ?></div>

    <div id="order-billing_method" class="payments"><?= $this->getChildHtml('billing_method') ?></div>
    <div id="order-shipping_method"><?= $this->getChildHtml('shipping_method') ?></div>

<?php if($this->getChild('card_validation')): ?>
    <div id="order-methods">
        <div id="order-card_validation" class="payments"><?= $this->getChildHtml('card_validation') ?></div>
    </div>
<?php endif ?>

    <?= $this->getChildHtml('gift_options') ?>

    <div class="entry-edit">
        <div class="entry-edit-head"><h4><?= Mage::helper('sales')->__('Order History') ?></h4></div>
        <fieldset id="order-comment"><?= $this->getChildHtml('comment') ?></fieldset>
    </div>

    <div class="entry-edit">
        <div class="entry-edit-head"><h4><?= Mage::helper('sales')->__('Order Totals') ?></h4></div>
        <div id="order-totals" class="order-totals"><?= $this->getChildHtml('totals') ?></div>
    </div>

</div>
