<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2018 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2020-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Page_Header $this */
?>
<div class="header-top">
    <a href="<?= $this->getHomeLink() ?>" class="logo" title="Maho <?= Mage::getMahoVersion() ?>">
        <svg viewBox="0 0 242 237" xmlns="http://www.w3.org/2000/svg"><path d="M199 34c4 0 8 4 8 8v77c0 46-38 84-85 84H43c-4 0-8-4-8-8v-82c0-43 36-79 80-79h84zm-79 29c-30 0-54 25-54 55a54 54 0 0 0 109 0c0-30-25-55-55-55z" fill="#d7df22"/></svg>
	</a>
    <div class="header-right">
        <ul id="usermenu">
        	<li onmouseover="this.classList.add('over')" onmouseout="this.classList.remove('over')" class="parent level0 usermenulabel">
        		<a href="#" onclick="return false" title="<?= $this->__('User Menu') ?>">
                    <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" id="burger">
                        <path fill="#FFFFFF" d="M31,21H9v-2h22V21z M31,17H9v-2h22V17z M31,25H9v-2h22V25z"></path>
                    </svg>
                </a>
			    <ul>
                    <li><a href="<?= Mage::helper("adminhtml")->getUrl("adminhtml/system_account") ?>"><span><?= $this->__("Logged in as %s", $this->escapeHtml($this->getUser()->getUsername())) ?></span></a></li>
			    	<li><a href="<?= Mage::getBaseUrl() ?>" target="_blank"><span><?= $this->__('View') . ': ' . $this->escapeHtml(Mage::app()->getStore()->getFrontendName()) ?></span></a></li>
			    	<li><a href="<?= $this->getLogoutLink() ?>"><span><?= $this->__('Log Out') ?></span></a></li>
		        </ul>
		    </li>
		</ul>
        <?php if (Mage::getStoreConfigFlag('admin/global_search/enable') && Mage::getSingleton('admin/session')->isAllowed('admin/global_search')): ?>
        <fieldset>
            <legend>Search</legend>
            <span id="global_search_indicator" class="autocomplete-indicator" style="display: none">
                <img src="<?= $this->getSkinUrl('images/loading.svg') ?>" alt="<?= Mage::helper('core')->quoteEscape($this->__('Loading...')) ?>" class="v-middle"/>
            </span>
            <?php $defSearch = $this->__('Global Record Search') ?>
            <input id="global_search" name="query" type="text" class="input-text" value="<?php if(!empty($query)): ?><?= $query ?><?php else: ?><?= Mage::helper('core')->quoteEscape($defSearch) ?><?php endif ?>" onfocus="if(this.value=='<?= Mage::helper('core')->quoteEscape($defSearch, true) ?>')this.value=''; " onblur="if(this.value=='')this.value='<?= $defSearch ?>';" autocomplete="off" />
            <div id="global_search_autocomplete" class="autocomplete" style="display:none"></div>
            <script type="text/javascript">
                document.getElementById('global_search').addEventListener('input', function() {
                    let query = this.value;
                    if (query.length < 2) {
                        document.getElementById('global_search_autocomplete').style.display = 'none';
                        return;
                    }

                    document.getElementById('global_search_indicator').style.display = 'inline-block';
                    fetch('<?= $this->getUrl('adminhtml/index/globalSearch') ?>?isAjax=true', {
                        method: 'POST',
                        headers:{
                            'Content-Type': 'application/x-www-form-urlencoded'
                        },
                        body: new URLSearchParams({
                            'query': query,
                            'form_key': FORM_KEY
                        })
                    })
                    .then(response => {
                        return response.text();
                    })
                    .then(htmlString => {
                        let autocomplete = document.getElementById('global_search_autocomplete');
                        autocomplete.style.display = 'block';
                        autocomplete.innerHTML = htmlString;
                        Array.from(document.querySelectorAll('#global_search_autocomplete li')).forEach(li => {
                            li.addEventListener('click', function() {
                                location.href = this.getAttribute('url');
                            });
                        });
                        document.getElementById('global_search_indicator').style.display = 'none';
                    })
                    .catch(error => {
                        alert(error);
                    });
                });
            </script>
        </fieldset>
        <?php endif ?>
    </div>
</div>
