<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Attribute options control
 *
 * @see Mage_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract
 * @var Mage_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract $this
 */
?>
<div>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li><?= $this->__('If you do not specify an option value for a specific store view then the default (Admin) value will be used.') ?></li>
        </ul>
    </li>
</ul>
</div>

<div class="entity-edit">
    <div class="entry-edit-head">
        <h4><?= $this->__('Manage Titles (Size, Color, etc.)') ?></h4>
    </div>
    <div class="box">
        <div class="hor-scroll">
            <table class="dynamic-grid" cellspacing="0" id="attribute-labels-table">
                <tr>
                <?php foreach ($this->getStores() as $_store): ?>
                    <th><?= $this->escapeHtml($_store->getName()) ?></th>
                <?php endforeach ?>
                </tr>
                <tr>
                    <?php $_labels = $this->getLabelValues() ?>
                    <?php foreach ($this->getStores() as $_store): ?>
                    <td>
                        <input class="input-text<?php if($_store->getId()==0): ?> required-entry<?php endif ?>" type="text" name="frontend_label[<?= $_store->getId() ?>]" value="<?= $this->escapeHtml($_labels[$_store->getId()]) ?>"<?php if ($this->getReadOnly()):?> disabled="disabled"<?php endif ?>/>
                    </td>
                    <?php endforeach ?>
                </tr>
            </table>
        </div>
    </div>
</div>
<br/>
<div class="entity-edit" id="manage-options-panel">
    <div class="entry-edit-head">
        <h4><?= $this->__('Manage Options (values of your attribute)') ?></h4>
    </div>
    <div class="box">
        <div class="hor-scroll">
            <table class="dynamic-grid" cellspacing="0" cellpadding="0">
                <tr id="attribute-options-table">
                <?php if ($this->isConfigurableSwatchesEnabled()): ?>
                    <th><?= $this->escapeHtml($this->__('Swatch')) ?></th>
                <?php endif ?>
                <?php foreach ($this->getStores() as $_store): ?>
                    <th><?= $this->escapeHtml($_store->getName()) ?></th>
                <?php endforeach ?>
                    <th><?= $this->__('Position') ?></th>
                    <th class="nobr a-center"><?= $this->escapeHtml($this->__('Is Default')) ?></th>
                    <th>
                        <?php if (!$this->getReadOnly()):?>
                            <?= $this->getAddNewButtonHtml() ?>
                        <?php endif ?>
                    </th>
                </tr>
            </table>
        </div>
        <input type="hidden" id="option-count-check" value="" />
    </div>
</div>

<template id="row-template">
    <tr class="option-row" title="ID: {{id}}">
        <?php if ($this->isConfigurableSwatchesEnabled()): ?>
        <td style="position:relative">
            <input type="hidden" disabled class="swatch-value" name="option[swatch][{{id}}]" value="{{swatch}}" />
            <input type="color" class="swatch-option input-color-html5 validate-hex-color-hash {{swatch_class}}" value="{{swatch}}" />
            <span class="swatch-delete" data-msg-delete="<?= $this->escapeHtml($this->__('Are you sure to delete this fallback color?')) ?>">X</span>
        </td>
        <?php endif ?>
        <?php foreach ($this->getStores() as $_store): ?>
        <td><input name="option[value][{{id}}][<?= $_store->getId() ?>]" value="{{store<?= $_store->getId() ?>}}" class="input-text<?php if($_store->getId()==0): ?> required-entry<?php endif ?>" type="text" <?php if ($this->getReadOnly()):?> disabled="disabled"<?php endif ?>/></td>
        <?php endforeach ?>
        <td><input class="input-text" type="text" name="option[order][{{id}}]" value="{{sort_order}}" <?php if ($this->getReadOnly()):?> disabled="disabled"<?php endif ?>/></td>
        <td class="a-center"><input class="input-radio" type="{{intype}}" name="default[]" value="{{id}}" {{checked}} <?php if ($this->getReadOnly()):?> disabled="disabled"<?php endif ?>/></td>
        <td class="a-left">
            <input type="hidden" class="delete-flag" name="option[delete][{{id}}]" value="" />
            <?php if (!$this->getReadOnly()):?>
                <?= $this->getDeleteButtonHtml() ?>
            <?php endif ?>
        </td>
    </tr>
</template>

<script>

const templateText = document.getElementById('row-template').innerHTML;

Validation.add('required-options-count', '<?= $this->jsQuoteEscape($this->__('Options is required')) ?>', (v) => !Validation.get('IsEmpty').test(v));

console.log(<?= json_encode($this->getOptionValues()) ?>);

document.addEventListener('DOMContentLoaded', () => {
        return;
    const optionsForm = new EavAttributeOptionsForm('manage-options-panel');

<?php foreach ($this->getOptionValues() as $value): ?>
    optionsForm.add(<?= $value->toJson() ?>);
<?php endforeach ?>
});
</script>
