<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php if ($this->getChildHtml()) :?>
<template id="gift_options_configure">
    <form id="gift_options_configuration_form" action="#" method="post">
        <?= $this->getChildHtml() ?>
    </form>
</template>
<div id="giftoptions_tooltip_window" class="gift-options-tooltip" style="display:none;">
    <div id="giftoptions_tooltip_window_content">&nbsp;</div>
</div>

<script>
    window.giftOptionsPopup = new GiftOptionsPopup();
//giftOptionsTooltip.setTooltipWindow('giftoptions_tooltip_window','giftoptions_tooltip_window_content');
</script>
<?php endif ?>
