<?php
/**
 * Maho
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://openmage.org)
 * @copyright   Copyright (c) 2024 Maho (https://mahocommerce.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Catalog_Category_Edit_Form $this */
?>

<div class="content-header">
    <h3><?= $this->escapeHtml($this->getHeader()) ?></h3>
    <p class="content-buttons form-buttons">
        <?= $this->getResetButtonHtml() ?>
        <?= $this->getCategoryId() ? $this->getDeleteButtonHtml() : '' ?>
        <?= $this->getAdditionalButtonsHtml() ?>
        <?= $this->getSaveButtonHtml() ?>
    </p>
</div>
<?php if($this->hasStoreRootCategory()): ?>
    <?= $this->getTabsHtml() ?>
<?php else: ?>
<div class="messages warning-msg">
    <?= Mage::helper('catalog')->__('Set root category for this store in the <a href="%s">configuration</a>', $this->getStoreConfigurationUrl()) ?>
</div>
<?php endif ?>

<form id="category_edit_form" action="<?= $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>" />
    <div id="category_tab_content"></div>
</form>

<script>
    window.categoryInfo = <?= $this->getCategoryInfoJson() ?>;
    console.log(window.categoryInfo);
</script>

     <!--
<script type="text/javascript">

<?php if(($block = $this->getLayout()->getBlock('category.product.grid')) && ($_gridJsObject=$block->getJsObjectName())): ?>

    var categoryProducts = $H(<?= $this->getProductsJson() ?>);
    $('in_category_products').value = categoryProducts.toQueryString();

    function registerCategoryProduct(grid, element, checked){
        if(checked){
            if(element.positionElement){
                element.positionElement.disabled = false;
                categoryProducts.set(element.value, element.positionElement.value);
            }
        }
        else{
            if(element.positionElement){
                element.positionElement.disabled = true;
            }
            categoryProducts.unset(element.value);
        }
        $('in_category_products').value = categoryProducts.toQueryString();
        grid.reloadParams = {'selected_products[]':categoryProducts.keys()};
    }
    function categoryProductRowClick(grid, event){
        var tdElement = Event.findElement(event, 'td');
        var isInput   = Event.element(event).tagName == 'INPUT';
        if(tdElement){
            var checkbox = Element.getElementsBySelector(tdElement, 'input');
            if(checkbox[0]){
                var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                <?= $_gridJsObject ?>.setCheckboxChecked(checkbox[0], checked);
            }
        }
    }
    function positionChange(event){
        var element = Event.element(event);
        if(element && element.checkboxElement && element.checkboxElement.checked){
            categoryProducts.set(element.checkboxElement.value, element.value);
            $('in_category_products').value = categoryProducts.toQueryString();
        }
    }

    var tabIndex = 1000;
    function categoryProductRowInit(grid, row){
        var checkbox = $(row).getElementsByClassName('checkbox')[0];
        var position = $(row).getElementsByClassName('input-text')[0];
        if(checkbox && position){
            checkbox.positionElement = position;
            position.checkboxElement = checkbox;
            position.disabled = !checkbox.checked;
            position.tabIndex = tabIndex++;
            Event.observe(position,'keyup',positionChange);
        }
    }


    <?= $_gridJsObject ?>.rowClickCallback = categoryProductRowClick;
    <?= $_gridJsObject ?>.initRowCallback = categoryProductRowInit;
    <?= $_gridJsObject ?>.checkboxCheckCallback = registerCategoryProduct;
    <?= $_gridJsObject ?>.rows.each(function(row){categoryProductRowInit(<?= $_gridJsObject ?>, row)});

<?php endif ?>
</script>
-->
